package com.github.smukherj1.masonry.server.models

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.Id
import java.time.LocalDateTime

@Entity
data class BlobUploadModel(
    @Id
    val uploadId: String,
    // Upload ID generated by server for an active upload stream. Used to detect
    // if the client is concurrently trying to upload to the same upload ID from
    // different streams which will make the server fail the upload because it can
    // corrupt the uploaded data.
    @Column(nullable = false)
    val serverUploadId: String,
    @Column(nullable = false)
    val createTime: LocalDateTime,
    @Column(nullable = false)
    val updateTime: LocalDateTime,
    @Column(nullable = false)
    val location: String,
    @Column(nullable = false)
    val nextOffset: Long,
    @Enumerated(EnumType.STRING)
    val uploadStatus: UploadStatus
)

enum class UploadStatus {
    UNKNOWN,
    ACTIVE,
    COMPLETED,
    FAILED
}